title: PYTHON - DESDE CERO
author: Mauroquil-bit
email: capacnote@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este curso está pensado para no programadores
  Se desarrollará durante 9 clases.
  
theme: minima

# social links
twitter_username: Mauroquil # DO NOT include the @ character, or else the build will fail!
github_username:  Mauroquil-bit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
